[package]
name = "stupid-connector"
version.workspace = true
edition.workspace = true

[dependencies]
stupid-core = { path = "../core" }
stupid-graph = { path = "../graph" }
stupid-rules = { path = "../rules" }
tracing = { workspace = true }
