apiVersion: v1
kind: Service
metadata:
  name: eisenbahn-gateway
  namespace: eisenbahn
  labels:
    app.kubernetes.io/name: eisenbahn-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: stupid-db
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: eisenbahn-gateway
  ports:
    - name: http
      port: 39100
      targetPort: http
      protocol: TCP
