[package]
name = "stupid-graph"
version.workspace = true
edition.workspace = true

[dependencies]
stupid-core = { path = "../core" }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
